server:
  port: 8080
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:15431/cleverDB
    password: 123123
    driver-class-name: org.postgresql.Driver
    username: cleverMan
  liquibase:
    enabled: true
    changeLog: db.changelog/changelog-master.xml
    liquibase-schema: public
session:
  provider:
    enabled: true
    black-list:
      - "hello"
      - "Hahha"
service-feign:
  clients:
    name: session-client
    url: 127.0.0.1:8081
    path: /v1/sessions