server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:15431/cleverDB
    password: 123123
    driver-class-name: org.postgresql.Driver
    username: cleverMan
  liquibase:
    enabled: true
    changeLog: db.changelog/create-channel.xml
    liquibase-schema: public
    default-schema: public