server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:15431/cleverDB
    password: 123123
    driver-class-name: org.postgresql.Driver
    username: cleverMan
  liquibase:
    changeLog: db.changelog/change-logs.xml
    liquibase-schema: public
    default-schema: service_liquibase