server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:15433/testSession
    password: 111111
    driver-class-name: org.postgresql.Driver
    username: cleverMan
  liquibase:
    change-log: db.changelog/changelog-master.xml
app:
  session:
    clean:
      enabled: true
      frequency: "0 0 * * * ?"